name: dtracsi
description: "Laporan Akhir Project | Andini Rahmatillah 2024"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  qr_flutter: ^4.1.0
  screenshot: ^2.5.0
  path_provider: ^2.1.3
  printing: ^5.12.0
  pdf: ^3.10.8
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.3
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/appbar/
    - assets/images/splash/
    - assets/svg/
    - assets/template.png


